project:
  type: website
  output-dir: docs

website:
  title: "Google Summer of Code 2025 - Quantum and Code"
  
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - text: Vanshaj Bindal
      - icon: github
        href: https://github.com/Vanshaj0429
      - icon: linkedin  
        href: https://www.linkedin.com/in/vanshaj-bindal-487953244/

format:
  html:
    theme: [cosmo]
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    html-math-method: katex
    page-layout: article
    margin-left: 2em
    margin-right: 2em

execute:
  freeze: auto